#
# Copyright (c) 2025, 2026, Ethan Meng <ethan@rapidcow.org>
#
# This module is free software; you can redistribute it
# and/or modify it under the same terms as Perl itself.
# See LICENSE at the root directory of your distribution
# for a copy of Perl's licenses.
#
=pod

=head1 NAME

Sort::Search - binary search on contiguous sorted ranges

=head1 SYNOPSIS

  use Sort::Search qw(
    bisectl bisectr bixectl bixectr
    blsrch0 brsrch0 blsrch1 brsrch1
    blsrch2 brsrch2 blsrchx brsrchx
  );

  bisectl { OK } ARRAY;   # leftmost TRUE (F to T)
  bisectr { OK } ARRAY;   # rightmost TRUE (T to F)
  bixectl { OK } ARRAY;   # any TRUE  (F to T)
  bixectr { OK } ARRAY;   # any TRUE  (T to F)

  blsrch0 { ORD } ARRAY;  # leftmost >= 0 (- to +)
  blsrch1 { ORD } ARRAY;  # leftmost > 0  (- to +)
  brsrch0 { ORD } ARRAY;  # rightmost >= 0 (+ to -)
  brsrch1 { ORD } ARRAY;  # rightmost > 0  (+ to -)

  blsrch2 { ORD } ARRAY;  # (blsrch0, blsrch1)
  brsrch2 { ORD } ARRAY;  # (brsrch0, brsrch1)
  blsrchx { ORD } ARRAY;  # any == 0  (- to +)
  brsrchx { ORD } ARRAY;  # any == 0  (+ to -)

=head1 DESCRIPTION

B<NOTE>:  If you are new to this module, I recommend
starting with L<Sort::Search::Cookbook>, which has
quick references and examples for common use cases.

=head2 Terminology

This module implements two classes of search algorithms,
which will named separately in this document as the
I<bisection method> and the (ordinary) I<binary search>
for distinction.  A brief definition follows.

=over

=item *

The I<bisection method> works with a monotonic predicate
(B<OK>) with a unique transition point from FALSE to TRUE, or
vice versa.

For example, the array C<[0, 1, 2, 3, 4]> with respect to the
predicate C<< $_ >= 2 >> transitions from FALSE at C<1> into
TRUE at C<2>, and the array C<[5, 4, 3, 2, 1]> with respect
to the predicate C<< $_ >= 3 >> transitions from TRUE at C<3>
to FALSE at C<2>.  We name the boundary between the two sides
of such a transition the I<bisection point>.

It is important to note that such a bisection point sits in
the (imaginary) gap between the boundary indices, and it is up
to you to decide which one you want so this module can address
that point in form of an index.  It is also important to note
that either one of these indices may not point to an actual
array element, and while this module retains information to
help you find out whether or not that is the case, it does not
interpret nor invalidate the found index in form of a sentinel
index (such as C<-1> or C<undef>).  So whenever the index you
receive makes no sense, think of it as one end of a bisection
point, and hopefully it will start to make sense. :)

=item *

The I<binary search> works with a C-like comparison function,
named the I<ordering> (B<ORD>), with two unique transition
points: one from negative to 0, and one from 0 to positive.
Such a function is typically constructed with respect to a target
value to be located within the array (hence the name "search").

For example, suppose we want to locate C<$x = 3> in the array
C<[1, 2, 3, 3, 4]>.  We can consider the ordering C<< $_ <=> $x >>,
which returns negatives for C<[1, 2]>, zeros for C<[3, 3]>, and
positives for C<[4]>.  We name the boundary between the negatives
and the zeros the I<lower bisection point>, and that between
the zeros and the positives the I<upper bisection point>.

=back

In both cases, we call the return value of the
predicate/ordering the I<comparison result>, or
C<$cmp> for short.

=head2 Orientation variants

For every function in the conventional direction (i.e.,
left-to-right, true-to-false, increasing), a dual variant
is provided.  The conventional and dual directions are
identified by the lowercase letter L and R.  To re-use
my examples, this:

  use Sort::Search qw(bisectl);
  my @A = ( 0, 1, 2, 3, 4 );
  print $A[ bisectl { $_ >= 2 } \@A ];

prints C<2> because the left-variants prefer to return
the leftmost index of the matching range C<[2, 3, 4]>,
or one past the final index (C<5>) if no such range exists.

  use Sort::Search qw(bisectr);
  my @B = ( 5, 4, 3, 2, 1 );
  print $B[ bisectr { $_ >= 3 } \@B ];

prints C<3> because the right-variants prefer to return
the rightmost index of the matching range C<[5, 4, 3]>,
or one below the initial index (C<-1>) if no such range
exists.  (Care should be taken in this specific case
as indexing by C<-1> wraps back to the last element.)

=head2 Lower/upper variants

For I<binary search> functions in particular, there are
the 0,1 variants corresponding to the aforementioned
I<lower bisection point> and I<upper bisection point>.
These points are best visualized by plotting the image
of the ordering and taking note of the range of elements
mapped to zero.  For instance, consider the first 13
decimal digits of pi (including the integer part)
arranged in increasing order as the haystack, and the
number C<$x = 5> as the needle.  Then the zeros (as
marked by "=" below) are bound by the boundary where
it meets the negatives ("<") and positives (">"):

  use Sort::Search qw(blsrch0 blsrch1 brsrch0 brsrch1);
  my (@a, $lb, $lx, $ub, $ux) = sort { $a <=> $b }
     ( sprintf("%.13f", 4*atan2(1,1)) =~ /[0-9]/g )[0..12];
  my $x = 5;

  $lb = blsrch0 {$_<=>$x} \@a;  $ux = blsrch1 {$_<=>$x} \@a;  print "[$lb,$ux)";
  #  (left lower bound)           (left upper bound)             =>  [6,  9  )
  #    first $_ >= $x  -.          ,-  first $_ > $x
  #                      \        /
  #    0  1  2  3  4  5 [6  7  8 [9  a  b  c   index of $_
  #    -  -  -  -  -  -  0  0  0  +  +  +  +   ord ($_ <=> $x)
  #    <<<<<<<<<<<<<<<<<<========------------
  #    1  1  2  3  3  4  5  5  5  6  8  9  9   value of $_
  #    -----------------========>>>>>>>>>>>>>
  #    +  +  +  +  +  +  0  0  0  -  -  -  -   ord ($x <=> $_)
  #    0  1  2  3  4  5] 6  7  8] 9  a  b  c   index of $_
  #                   /        \
  #   last $x > $_  -'          `-  last $x >= $_
  # (right lower bound)            (right upper bound)           =>  (  5,  8]
  $lx = brsrch1 {$x<=>$_} \@a;  $ub = brsrch0 {$x<=>$_} \@a;  print "($lx,$ub]";

The 0 variants (B<blsrch0>, B<brsrch0>) return the
inclusive bounds for when ordering transitions from
"-" to "0", while the 1 variants (B<blsrch1>, B<brsrch1>)
return the exclusive bounds for when the ordering
transitions from "0" to "+".  For left search in
particular, B<blsrch0> is the inclusive lower bound,
and B<blsrch1> is the exclusive upper bound.  The 2
variants (B<blsrch2>, B<brsrch2>) return both inclusive
and exclusive bounds at once, in that order; in scalar
context, they return the absolute difference which
corresponds to the range of equal values (i.e. the "0"s).

A more compact (albeit possibly obscure) characterization
of the 0,1 variants is that they are the composition of
the predicates C<< &$ord >= 0 >> and C<< &$ord > 0 >>
on top of the bisection functions of the corresponding
orientations.  Note that this formal characterization
intentionally makes no mention of consistency with the
total order from which it is derived; in particular it is
possible to extend the notion of equality by mapping any
contiguous region one wishes to find to "0", provided
that it is properly bounded by "+" and "-".

Another thing to note is that, given the same underlying
array, the ordering should be reversed when orientation
is flipped.  Usually when you could flip the operands to
achieve this, as I have shown above with C<< $_ <=> $x >>
for left search and C<< $x <=> $_ >> for right search.
But in restrained cases where either (1) you don't have
access to both operands and have to work with the ordering
as a blackboxed unary function of C<$_>, or (2) the
needle is not interchangeable with C<$_> (say, when the
needle is a field of a larger structure), you can negate
the ordering instead.


=head2 Existence variants

The bisection and the 0 variants have x variants which
return as soon as it finds a match.
(Mnemonic: "x" stands for "eXists".)

=over

=item *

B<bixectl> is a modified version of B<bisectl> that
returns any index for which the predicate returns TRUE.
In the case that the predicate attains TRUE at exactly
one point or never attains TRUE, they behave identically.
For B<bixectr>, it's the same against B<bisectr>.

=item *

B<blsrchx> is a modified version of B<blsrch0> that
returns any index for which the predicate returns 0.
In the case that the ordering attains 0 at exactly
one point or skips it entirely, they behave identically.
For B<brsrchx>, it's the same against B<brsrch0>.

=back

=begin VOID

XXX: Define search range???  (oh wait it's in the
top part of Subroutines.... (is it good though???))

The observant reader will quickly notice that the L-R
variants make each other redundant.

You are free to stick to one variant, then add 1 to or
subtract 1 from the index to derive the other. :)

For reference, the following relations should hold:

  bisectl { OK } ARRAY[,LO[,HI+1]]   ==  1 + bisectr { !OK } ARRAY[,HI[,LO-1]];
  bixectl { OK } ARRAY[,LO[,HI+1]]   ==  1 + bixectr { !OK } ARRAY[,HI[,LO-1]];
  blsrch0 { ORD } ARRAY[,LO[,HI+1]]   ==  1 + brsrch1 { -ORD } ARRAY[,HI[,LO-1]];
  blsrch1 { ORD } ARRAY[,LO[,HI+1]]   ==  1 + brsrch0 { -ORD } ARRAY[,HI[,LO-1]];
  blsrch2 { ORD } ARRAY[,LO[,HI+1]]    ==   brsrch2 { -ORD } ARRAY[,HI[,LO-1]];
                                     (in scalar context)

=end VOID

=head1 SUBROUTINES

All subroutines are exported on-demand.  All subroutines
share the same interface for input and output described in
L</COMMON INTERFACE>.  The general behavior of each subroutine
on arbitrary ranges is described, but in the common form that
I anticipate most people to use (calling with the array form
with no explicit limits, and returning in scalar context),
it is sufficient to know the following:

=over

=item *

For left searches (subroutines containing the letter "l"),
B<$lo> is the index of the leftmost/first array element and
B<$hi> is one more than the rightmost/final array element.
Notably, B<$hi> is the fallback index when search finds a
bisection point to the right of the whole array.

=item *

For right searches (subroutines containing the letter "r"),
B<$lo> is one less than the index of the leftmost/first array
element and B<$hi> is the rightmost/final array element.
Notably, B<$lo> is the fallback index when search finds a
bisection point to the left of the whole array.

=back

To re-re-use the examples from the L</DESCRIPTION> section,
the implicit search range for C<< bisectl { ... } \@A >> is
C<$lo = 0> and C<$hi = 5>, and the implicit search range for
C<< bisectr { ... } \@B >> is C<$lo = -1> and C<$hi = 4>.
Note that the two searches have different fallback indices:
C<$hi = 5> for the left search and C<$lo = -1> for the right
search.

=over

=item B<bisectl { OK } ARRAY>

=item B<bixectl { OK } ARRAY>

Perform left bisection with respect to a predicate B<OK> on the
half-open interval C<[$lo, $hi)>, where C<$lo> precedes C<$hi>
in the argument list.  The prototype is C<&$;$$>.

The predicate should be increasing over every pair of adjacent indices
it is defined on.  That is, true values always follow false values:

   F F F ... F T T T   ok(x)
   0 1 2     6 7 8 9      x

Let C<$ok> denote the predicate, and set C<< $ok->($hi) = 1 >>.
The return value of B<bisectl> is the unique index C<$x> on the
closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ok->($x) >> is true.

=item *

For all valid index C<< $y < $x >>, it follows that C<< $ok->($y) >> is false.

=back

The return value of B<bixectl> is any index satisfying the first constraint.

If the interval C<[$lo, $hi]> is empty, return C<$hi>.

=item B<bisectr { OK } ARRAY>

=item B<bixectr { OK } ARRAY>

Perform right bisection with respect to a predicate B<OK> on the
half-open interval C<($lo, $hi]>, where C<$hi> precedes C<$lo>
in the argument list.  The prototype is C<&$;$$>.

The predicate should be decreasing over every pair of adjacent indices
it is defined on.  That is, true values always precede false values:

   T T T ... T F F F   ok(x)
   0 1 2     6 7 8 9      x

Let C<$ok> denote the predicate, and set C<< $ok->($lo) = 1 >>.
The return value of B<bisectr> is the unique index C<$x> on the
closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ok->($x) >> is true.

=item *

For all valid index C<< $y > $x >>, it follows that C<< $ok->($y) >> is false.

=back

The return value of B<bixectr> is any index satisfying the first constraint.

If the interval C<[$lo, $hi]> is empty, return C<$lo>.

=back

In general, a return value of C<$hi> (for left bisection) and
C<$lo> (for right bisection) is not meaningful as it is the only
index taken to be true for granted.  Caller should handle it
separately, or check if the comparison result and/or element
are defined by calling in list context.

=over

=item B<blsrch0 { ORD } ARRAY>

=item B<blsrchx { ORD } ARRAY>

=item B<blsrch1 { ORD } ARRAY>

=item B<blsrch2 { ORD } ARRAY>

Perform binary left search with respect to an ordering B<ORD> on
the half-open interval C<[$lo, $hi)>, where C<$lo> precedes C<$hi>
in the argument list.  The prototype is C<&$;$$>.

The sign of the ordering should be increasing over every pair of
adjacent indices it is defined on.  That is, C<< <0 >> (negative)
precedes C<< =0 >> (zero), which precedes C<< >0 >> (positive).

Let C<$ord> denote the ordering and set C<< $ord->($hi) = +Infinity >>.
The return value of B<blsrch0> is the unique index C<$lb> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($lb) >= 0 >>.

=item *

For all valid index C<< $x < $lb >>, it follows that C<< $ord->($x) < 0 >>.
As a result, C<$lb> is the first instance where C<< $ord >= 0 >>,
while C<$lb - 1> is the last instance where C<< $ord < 0 >>.
(Compare this to C<$lx> returned by B<brsrch1>.)

=back

The return value of B<blsrchx> is any index C<$x> satisfying
C<< $ord->($x) == 0 >>, but if one could not be found,
it returns the same result as C<blsrch0>.

The return value of B<blsrch1> is the unique index C<$ux>
on the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($ux) > 0 >>.

=item *

For all valid index C<< $x < $ux >>, it follows that C<< $ord->($x) <= 0 >>.
As a result, C<$ux> is the first instance where C<< $ord > 0 >>,
while C<$ux - 1> is the last instance where C<< $ord <= 0 >>.
(Compare this to C<$ub> returned by B<brsrch0>.)

=back

In list context, B<blsrch2> returns both C<$lb> and C<$ux>,
in that order.  In scalar context, it returns the nonnegative
difference C<$ux - $lb>, which equals the number of elements
for which C<$ord == 0>.

=item B<brsrch0 { ORD } ARRAY>

=item B<brsrchx { ORD } ARRAY>

=item B<brsrch1 { ORD } ARRAY>

=item B<brsrch2 { ORD } ARRAY>

Perform binary right search with respect to an ordering B<ORD> on
the half-open interval C<($lo, $hi]>, where C<$hi> precedes C<$lo>
in the argument list.  The prototype is C<&$;$$>.

The sign of the ordering should be decreasing over every pair of
adjacent indices it is defined on.  That is, C<< >0 >> (positive)
precedes C<< =0 >> (zero), which precedes C<< <0 >> (negative).

Let C<$ord> denote the ordering and set C<< $ord->($lo) = +Infinity >>.
The return value of B<brsrch0> is the unique index C<$ub> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($ub) >= 0 >>.

=item *

For all valid index C<< $x > $ub >>, it follows that C<< $ord->($x) < 0 >>.
As a result, C<$ub> is the last instance where C<< -$ord <= 0 >> and
C<$ub + 1> is the first instance where C<< -$ord > 0 >>.
(Compare this to C<$ux> returned by B<blsrch1>.)

=back

The return value of B<brsrchx> is any index C<$x> satisfying
C<< $ord->($x) == 0 >>, but if one could not be found,
it returns the same result as C<brsrch0>.

The return value of B<brsrch1> is the unique index C<$lx> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($lx) > 0 >>.

=item *

For all valid index C<< $x > $lx >>, it follows that C<< $ord->($x) <= 0 >>.
As a result, C<$lx> is the last instance where C<< -$ord < 0 >> and
C<$lx + 1> is the first instance where C<< -$ord >= 0 >>.
(Compare this to C<$lb> returned by B<blsrch0>.)

=back

In list context, B<brsrch2> returns both C<$ub> and C<$lx>,
in that order.  In scalar context, it returns the nonnegative
difference C<$ub - $lx>, which equals the number of elements
for which C<$ord == 0>.

=back

=head1 COMMON INTERFACE

  # TODO !

=head1 CAVEATS

Prior to Perl 5.8.0, arithmetic precision is limited to the
precision of floating-points.  This precision is dependent on
C<nv_preserves_uv_bits> of your perl, which is 53 for x86_64.
Bounds greater than C<2 ** nv_preserves_uv_bits> will show
round-off errors and, in some cases, fail to converge at all.
L<Math::BigInt> will be necessary in such cases, even if
both bounds technically fit in an IV/UV.

=head1 SEE ALSO

L<List::MoreUtils>, L<List::Search>, L<List::BinarySearch>,
L<List::BinarySearch::XS>.

=head1 LINKS

=over

=item *

Home page: L<https://foss.rapidcow.org/CPAN/Sort-Search/>

=item *

Git repository: L<https://codeberg.org/rapidcow/p5-Sort-Search>

=back

=cut
