#
# Copyright (c) 2025, 2026, Ethan Meng <ethan@rapidcow.org>
#
# This module is free software; you can redistribute it
# and/or modify it under the same terms as Perl itself.
# See LICENSE at the root directory of your distribution
# for a copy of Perl's licenses.
#
=pod

=head1 NAME

Sort::Search - binary search on contiguous sorted ranges

=head1 SYNOPSIS

  use Sort::Search qw(
      bisectl bisectr bixectl bixectr
      blsrch0 brsrch0 blsrch1 brsrch1
      blsrch2 brsrch2 blsrchx brsrchx
  );

  bisectl { OK } ARRAY;   # leftmost TRUE (F to T)
  bisectr { OK } ARRAY;   # rightmost TRUE (T to F)
  bixectl { OK } ARRAY;   # any TRUE  (F to T)
  bixectr { OK } ARRAY;   # any TRUE  (T to F)

  blsrch0 { ORD } ARRAY;  # leftmost >= 0 (- to +)
  blsrch1 { ORD } ARRAY;  # leftmost > 0  (- to +)
  brsrch0 { ORD } ARRAY;  # rightmost >= 0 (+ to -)
  brsrch1 { ORD } ARRAY;  # rightmost > 0  (+ to -)

  blsrch2 { ORD } ARRAY;  # (blsrch0, blsrch1)
  brsrch2 { ORD } ARRAY;  # (brsrch0, brsrch1)
  blsrchx { ORD } ARRAY;  # any == 0  (- to +)
  brsrchx { ORD } ARRAY;  # any == 0  (+ to -)

=head1 DESCRIPTION

B<NOTE>:  If you are new to this module, I recommend
starting with L<Sort::Search::Cookbook>, which has
quick references and examples for common use cases.

=head2 Terminology

This module implements two classes of search algorithms,
which will be named separately in this document as the
I<bisection method> and the (ordinary) I<binary search>
for distinction.  A brief definition follows.

=over

=item *

The I<bisection method> works with a monotonic predicate
(B<OK>) with a unique transition point from FALSE to TRUE, or
vice versa.

For example, the array C<[0, 1, 2, 3, 4]> with respect to the
predicate C<< $_ >= 2 >> transitions from FALSE at C<1> into
TRUE at C<2>, and the array C<[5, 4, 3, 2, 1]> with respect
to the predicate C<< $_ >= 3 >> transitions from TRUE at C<3>
to FALSE at C<2>.  We name the boundary between the two sides
of such a transition the I<bisection point>.

It is important to note that such a bisection point sits in
the (imaginary) gap between the boundary indices, and it is up
to you to decide which one you want so this module can address
that point in form of an index.  It is also important to note
that either one of these indices may not point to an actual
array element, and while this module retains information to
help you find out whether or not that is the case, it does not
interpret nor invalidate the found index in form of a sentinel
index (such as C<-1> or C<undef>).  So whenever the index you
receive makes no sense, think of it as one end of a bisection
point, and hopefully it will start to make sense. :)

=item *

The I<binary search> works with a C-like comparison function,
named the I<ordering> (B<ORD>), with two unique transition
points: one from negative to 0, and one from 0 to positive.
Such a function is typically constructed with respect to a target
value to be located within the array (hence the name "search").

For example, suppose we want to locate C<$x = 3> in the array
C<[1, 2, 3, 3, 4]>.  We can consider the ordering C<< $_ <=> $x >>,
which returns negatives for C<[1, 2]>, zeros for C<[3, 3]>, and
positives for C<[4]>.  This ordering is said to be I<increasing>,
which is suitable for left searches (such as B<blsrch0>).
We name the boundary between the negatives and the zeros the
I<lower bisection point>, and that between the zeros and the
positives the I<upper bisection point>.

Note the asymmetrical treatment of target and array element.
In certain cases, the target may not need to undergo the
same treatment that the element does if the target is already
processed.  For example, suppose we want to locate C<$y = d>
case-insensitively in the array C<[x, D, d, c, C]>.  The
ordering C<< lc($_) cmp $y >> returns positives for C<[x]>,
zeros for C<[D, d]>, and negatives for C<[c, C]>.  (Here, since
C<$y> is already lowercase, there is no need to call C<lc($y)>.)
In contrast, this ordering is said to be I<decreasing>, and is
suitable for right searches (such as B<brsrch0>).

An ordering, in fact, need not be associated with any specific
target at all.  To the binary search function, it is merely
a unary function like the predicate (besides the fact that
the latter is concerned with finding truths, while the former,
finding zeros).

=back

In both cases, we call the return value of the
predicate / ordering the I<comparison result>, or
C<$cmp> for short.

=head2 Orientation variants

For every function in the conventional direction (i.e.,
left-to-right, false-to-true, increasing), a dual variant
is provided.  The conventional and dual directions are
identified by the lowercase letter "L" and "R".

Broadly speaking, all "L" variants return the leftmost instance
on an increasing image; and all "R" variants return the rightmost
instance on a decreasing image.  In the context of bisection
method, increasing means that the predicate goes from false to
true, and decreasing means true to false.  In the context of
binary search, increasing means C<- 0 +>, and decreasing means
C<+ 0 ->.

To re-use my examples, this:

  use Sort::Search qw(bisectl);
  #         0  1  2  3  4      [index]
  my @A = ( 0, 1, 2, 3, 4 );
  #         F  F  T  T  T      [image]
  print scalar bisectl { $_ >= 2 } \@A;

prints C<2> because the "L" variants prefer to return
the leftmost index of the matching range C<[2, 3, 4]>,
or one past the final index (C<5>) if no such range exists.

  use Sort::Search qw(bisectr);
  #         0   1   2   3   4      [index]
  my @B = ( 0, -1, -2, -3, -4 );
  #         T   T   T   F   F      [image]
  print scalar bisectr { $_ >= -2 } \@B;

also prints C<2> because the "R" variants prefer to return
the rightmost index of the matching range C<[0, -1, -2]>, or
one below the initial index (C<-1>) if no such range exists.
(Care should be taken in this specific case as indexing by
C<-1> wraps back to the last element.)

Without getting too far ahead of myself, the semantics for
the searches are identical:

  use Sort::Search qw(blsrch0 brsrch0);
  #           0  1  2  3  4    [index]
  my @p =   ( 5, 6, 7, 7, 9 );
  #           -  -  0  0  +    [image]
  print scalar blsrch0 { $_ <=> 7 } \@p;

  #           0  1  2  3  4    [index]
  my @q = qw( x  D  d  c  C );
  #           +  0  0  -  -    [image]
  print scalar brsrch0 { lc($_) cmp 'd' } \@q;

Here, the "L" variant returns leftmost instance of
C<0 +>, and the "R" variant returns the rightmost
instance of C<+ 0>.  Both of them still print C<2>.

=head2 Lower / upper variants

For I<binary search> functions in particular, there are
the 0,1 variants corresponding to the aforementioned
I<lower bisection point> and I<upper bisection point>.
These points are best visualized by plotting the image
of the ordering and taking note of the range of elements
mapped to zero.  For instance, consider the first 13
decimal digits of pi (including the integer part)
arranged in increasing order as the haystack, and the
number C<$x = 5> as the needle.  Then the zeros (as
marked by "=" below) are bound by the boundary where
it meets the negatives ("<") and positives (">"):

  use Sort::Search qw(blsrch0 blsrch1 brsrch0 brsrch1);
  my (@a, $lb, $lx, $ub, $ux) = sort { $a <=> $b }
     ( sprintf("%.13f", 4*atan2(1,1)) =~ /[0-9]/g )[0..12];
  my $x = 5;

  $lb = blsrch0 {$_<=>$x} \@a;  $ux = blsrch1 {$_<=>$x} \@a;  print "[$lb,$ux)";
  #  (left lower bound)           (left upper bound)             =>  [6,  9  )
  #    first $_ >= $x  -.          ,-  first $_ > $x
  #                      \        /
  #    0  1  2  3  4  5 [6  7  8 [9  a  b  c   index of $_
  #    -  -  -  -  -  -  0  0  0  +  +  +  +   ord ($_ <=> $x)
  #    <<<<<<<<<<<<<<<<<<========------------
  #    1  1  2  3  3  4  5  5  5  6  8  9  9   value of $_
  #    -----------------========>>>>>>>>>>>>>
  #    +  +  +  +  +  +  0  0  0  -  -  -  -   ord ($x <=> $_)
  #    0  1  2  3  4  5] 6  7  8] 9  a  b  c   index of $_
  #                   /        \
  #   last $x > $_  -'          `-  last $x >= $_
  # (right lower bound)            (right upper bound)           =>  (  5,  8]
  $lx = brsrch1 {$x<=>$_} \@a;  $ub = brsrch0 {$x<=>$_} \@a;  print "($lx,$ub]";

The 0 variants (B<blsrch0>, B<brsrch0>) return the
inclusive bounds for when ordering transitions from
"-" to "0", while the 1 variants (B<blsrch1>, B<brsrch1>)
return the exclusive bounds for when the ordering
transitions from "0" to "+".  For left search in
particular, B<blsrch0> is the inclusive lower bound,
and B<blsrch1> is the exclusive upper bound.  The 2
variants (B<blsrch2>, B<brsrch2>) return both inclusive
and exclusive bounds at once, in that order; in scalar
context, they return the absolute difference which
corresponds to the range of equal values (i.e. the zeros).

A more compact (albeit possibly obscure) characterization
of the 0,1 variants is that they are the composition of
the predicates C<< &$ord >= 0 >> and C<< &$ord > 0 >>
on top of the bisection functions of the corresponding
orientations.  This formal characterization does, however,
reinforce the idea that an ordering is merely a predicate
with a different specialized output; and it is up to the
caller to define and interpret the meaning of the zeros.

Another thing to note is that, given the same underlying
array, the ordering should be reversed when the orientation
is flipped.  Usually you can flip the operands to achieve
this, as I have shown above with C<< $_ <=> $x >> for left
search and C<< $x <=> $_ >> for right search.  But in cases
where you don't have access to both operands and have to
work with the ordering as a blackboxed unary function of
C<$_>, you can negate the ordering instead.


=head2 Existence variants

The bisection and the 0 variants have x variants which
return as soon as they find a match.
(Mnemonic: "x" stands for "eXists".)

=over

=item *

B<bixectl> is a modified version of B<bisectl> that
returns any index for which the predicate returns TRUE.
In the case that the predicate attains TRUE at exactly
one point or never attains TRUE, they behave identically.
For B<bixectr>, it's the same against B<bisectr>.

=item *

B<blsrchx> is a modified version of B<blsrch0> that
returns any index for which the ordering returns 0.
In the case that the ordering attains 0 at exactly
one point or skips it entirely, they behave identically.
For B<brsrchx>, it's the same against B<brsrch0>.

=back

=begin VOID

XXX: Define search range???  (oh wait it's in the
top part of Subroutines.... (is it good though???))

The observant reader will quickly notice that the L-R
variants make each other redundant.

You are free to stick to one variant, then add 1 to or
subtract 1 from the index to derive the other. :)

For reference, the following relations should hold:

  bisectl { OK } ARRAY[,LO[,HI+1]]   ==  1 + bisectr { !OK } ARRAY[,HI[,LO-1]];
  bixectl { OK } ARRAY[,LO[,HI+1]]   ==  1 + bixectr { !OK } ARRAY[,HI[,LO-1]];
  blsrch0 { ORD } ARRAY[,LO[,HI+1]]   ==  1 + brsrch1 { -ORD } ARRAY[,HI[,LO-1]];
  blsrch1 { ORD } ARRAY[,LO[,HI+1]]   ==  1 + brsrch0 { -ORD } ARRAY[,HI[,LO-1]];
  blsrch2 { ORD } ARRAY[,LO[,HI+1]]    ==   brsrch2 { -ORD } ARRAY[,HI[,LO-1]];
                                     (in scalar context)

=end VOID

=head1 FUNCTIONS

All functions share the same interface for input and output
(with the exception of the outputs of B<blsrch2> and
B<brsrch2>, which still share the same input mechanism
nonetheless).  The full story of that will be deferred to
L</COMMON INTERFACE>, though it helps to establish a few
concepts.

Up until this point I have been exclusively talking about
searches with an implied I<search range> on entire arrays.
What follows is a formal definition.  Like lower and upper
bounds, the search range is asymmetrically identified by
a low index (C<$lo>) and a high index (C<$hi>):

=over

=item *

A left search is presented with the challenge of finding
a candidate with index on the range C<[$lo, $hi)>; and
should it fail to meet that challenge, it yields C<$hi>.
Previously, whenever a left search was performed on an array
named, say, C<@array>, the range had been C<$lo = 0> (lowest
index) and C<$hi = $#array + 1> (one above the highest index).

=item *

A right search is presented with the challenge of finding
a candidate with index on the range C<($lo, $hi]>, and yield
C<$lo> on failure.  Previously, whenever a right search was
performed on C<@array>, the range had been C<$hi = $#array>
(highest index) and C<$lo = -1> (one below the lowest index).

=back

The remainer of this section will make explicit mentions
of the search range to explain the mathematical contract
by which the binary search algorithm should abide.

Also: for convenience, the predicate and ordering are written
as simple unary functions on the array index.  But know
that this isn't how they are called (well, it's not really
lying; C<$_[0]> would be the index.  But C<$_> is more
versatile and aliased to the array element itself in the
array form.  Either way, the part where C<$_> is localized
and aliased is left out to your imagination. :)

=over

=item B<bisectl { OK } ARRAY>

=item B<bixectl { OK } ARRAY>

Perform left bisection with respect to a predicate B<OK> on the
half-open interval C<[$lo, $hi)>, where C<$lo> precedes C<$hi>
in the argument list.  The prototype is C<&$;$$>.

The predicate should be increasing over every pair of adjacent indices
it is defined on.  That is, true values always follow false values:

  F F F ... F T T T   ok(x)
  0 1 2     6 7 8 9      x

Let C<$ok> denote the predicate, and set C<< $ok->($hi) = 1 >>.
The return value of B<bisectl> is the unique index C<$x> on the
closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ok->($x) >> is true.

=item *

For every valid index C<< $y < $x >>, it follows that C<< $ok->($y) >> is false.

=back

The return value of B<bixectl> is any index satisfying the first constraint.

If the interval C<[$lo, $hi]> is empty, return C<$hi>.

=item B<bisectr { OK } ARRAY>

=item B<bixectr { OK } ARRAY>

Perform right bisection with respect to a predicate B<OK> on the
half-open interval C<($lo, $hi]>, where C<$hi> precedes C<$lo>
in the argument list.  The prototype is C<&$;$$>.

The predicate should be decreasing over every pair of adjacent indices
it is defined on.  That is, true values always precede false values:

  T T T ... T F F F   ok(x)
  0 1 2     6 7 8 9      x

Let C<$ok> denote the predicate, and set C<< $ok->($lo) = 1 >>.
The return value of B<bisectr> is the unique index C<$x> on the
closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ok->($x) >> is true.

=item *

For every valid index C<< $y > $x >>, it follows that C<< $ok->($y) >> is false.

=back

The return value of B<bixectr> is any index satisfying the first constraint.

If the interval C<[$lo, $hi]> is empty, return C<$lo>.

=back

In general, a return value of C<$hi> (for left bisection) and
C<$lo> (for right bisection) may not be meaningful as it is the
only index taken to be true for granted.  Caller should examine
it separately, or check if the comparison result and/or element
are defined by calling in list context.

=over

=item B<blsrch0 { ORD } ARRAY>

=item B<blsrchx { ORD } ARRAY>

=item B<blsrch1 { ORD } ARRAY>

=item B<blsrch2 { ORD } ARRAY>

Perform binary left search with respect to an ordering B<ORD> on
the half-open interval C<[$lo, $hi)>, where C<$lo> precedes C<$hi>
in the argument list.  The prototype is C<&$;$$>.

The sign of the ordering should be increasing over every pair of
adjacent indices it is defined on.  That is, C<< <0 >> (negative)
precedes C<< =0 >> (zero), which precedes C<< >0 >> (positive).

Let C<$ord> denote the ordering and set C<< $ord->($hi) = +Infinity >>.
The return value of B<blsrch0> is the unique index C<$lb> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($lb) >= 0 >>.

=item *

For every valid index C<< $x < $lb >>, it follows that C<< $ord->($x) < 0 >>.
As a result, C<$lb> is the first instance where C<< $ord >= 0 >>,
while C<$lb - 1> is the last instance where C<< $ord < 0 >>.
(Compare this to C<$lx> returned by B<brsrch1>.)

=back

The return value of B<blsrchx> is any index C<$x> satisfying
C<< $ord->($x) == 0 >>, but if one could not be found,
it returns the same result as C<blsrch0>.

The return value of B<blsrch1> is the unique index C<$ux>
on the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($ux) > 0 >>.

=item *

For every valid index C<< $x < $ux >>, it follows that C<< $ord->($x) <= 0 >>.
As a result, C<$ux> is the first instance where C<< $ord > 0 >>,
while C<$ux - 1> is the last instance where C<< $ord <= 0 >>.
(Compare this to C<$ub> returned by B<brsrch0>.)

=back

In list context, B<blsrch2> returns both C<$lb> and C<$ux>,
in that order.  In scalar context, it returns the nonnegative
difference C<$ux - $lb>, which equals the number of elements
for which C<$ord == 0>.

=item B<brsrch0 { ORD } ARRAY>

=item B<brsrchx { ORD } ARRAY>

=item B<brsrch1 { ORD } ARRAY>

=item B<brsrch2 { ORD } ARRAY>

Perform binary right search with respect to an ordering B<ORD> on
the half-open interval C<($lo, $hi]>, where C<$hi> precedes C<$lo>
in the argument list.  The prototype is C<&$;$$>.

The sign of the ordering should be decreasing over every pair of
adjacent indices it is defined on.  That is, C<< >0 >> (positive)
precedes C<< =0 >> (zero), which precedes C<< <0 >> (negative).

Let C<$ord> denote the ordering and set C<< $ord->($lo) = +Infinity >>.
The return value of B<brsrch0> is the unique index C<$ub> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($ub) >= 0 >>.

=item *

For every valid index C<< $x > $ub >>, it follows that C<< $ord->($x) < 0 >>.
As a result, C<$ub> is the last instance where C<< -$ord <= 0 >> and
C<$ub + 1> is the first instance where C<< -$ord > 0 >>.
(Compare this to C<$ux> returned by B<blsrch1>.)

=back

The return value of B<brsrchx> is any index C<$x> satisfying
C<< $ord->($x) == 0 >>, but if one could not be found,
it returns the same result as C<brsrch0>.

The return value of B<brsrch1> is the unique index C<$lx> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($lx) > 0 >>.

=item *

For every valid index C<< $x > $lx >>, it follows that C<< $ord->($x) <= 0 >>.
As a result, C<$lx> is the last instance where C<< -$ord < 0 >> and
C<$lx + 1> is the first instance where C<< -$ord >= 0 >>.
(Compare this to C<$lb> returned by B<blsrch0>.)

=back

In list context, B<brsrch2> returns both C<$ub> and C<$lx>,
in that order.  In scalar context, it returns the nonnegative
difference C<$ub - $lx>, which equals the number of elements
for which C<$ord == 0>.

=back

=head1 COMMON INTERFACE

This section describes the input forms (index, ARRAY, and CODE),
common to all functions, and the output forms (scalar and list
contexts) for the 2-variants (i.e. B<blsrch2> and B<brsrch2>)
and for everyone else.

=head2 Input forms

The input form determines the meaning of C<$_> in the predicate
/ ordering callback, though C<$_[0]> stays the current index in
all three scenarios.

=over

=item B<index form>

  bisectl { OK }  [undef,] [LO,] HI;  # also: bixectl
  blsrch0 { ORD } [undef,] [LO,] HI;  # also: blsrchx blsrch1 blsrch2
  bisectr { OK }  [undef,] HI [,LO];  # also: bixectr
  brsrch0 { ORD } [undef,] HI [,LO];  # also: brsrchx brsrch1 brsrch2

As the name implies, C<$_> here is aliased to the index
C<$_[0]> itself with no additional mapping.  The index
form is inferred whenever the first argument following
is neither an ARRAY nor a CODE reference, though it may be
explicitly pinned by prefixing the index with C<undef>:

  bisectr { $_ * $_ <= 2025 }        2025;  # Implicit
  bisectr { $_ * $_ <= 2025 } undef, 2025;  # Explicit

(There should not be a need to prefix a bigint with C<undef>:
as far as I can tell, L<Math::BigInt> had always been either
a blessed SCALAR or a blessed HASH, but never blessed ARRAY.
Should my naive assumption break however, explicit form is
your only escape hatch.)

Recall that left search probes C<[$lo, $hi)> while right
search probes C<($lo, $hi]>.  In either search orientation,
C<$hi> is required in this form and is obtained from the
first argument.  C<$lo> is inferred if omitted: the default
is 0 for left search and -1 for right search.  That is to
say, C<bisectr { ... } N> searches on C<(-1, N]>, while
C<bisectl { ... } N> searches on C<[0, N)>.

=item B<ARRAY form>

  bisectl { OK }  ARRAY [,[LO,] HI];  # also: bixectl
  blsrch0 { ORD } ARRAY [,[LO,] HI];  # also: blsrchx blsrch1 blsrch2
  bisectr { OK }  ARRAY [,HI [,LO]];  # also: bixectr
  brsrch0 { ORD } ARRAY [,HI [,LO]];  # also: brsrchx brsrch1 brsrch2

When given an array, C<$_> is instead aliased to the
array element instead.  Omitting C<$lo> is subject to
inference as with the index form, however this time,
C<$hi> too can be inferred: the default is one past
the last index of the passed array for left search
(or equivalently, the size) and the last index itself
for right search.

Note that the scalar prototype enables you to pass
C<@array> directly:

  my ($want, @array, $lo);
  my $hi = blsrch1 { $_ <=> $want }
             \@array, $lo, @array;
  #                        ^^^^^^
  # No "scalar" or 0+ necessary here!

=item B<CODE form>

  bisectl { OK }  CODE, [LO,] HI;  # also: bixectl
  blsrch0 { ORD } CODE, [LO,] HI;  # also: blsrchx blsrch1 blsrch2
  bisectr { OK }  CODE, HI [,LO];  # also: bixectr
  brsrch0 { ORD } CODE, HI [,LO];  # also: brsrchx brsrch1 brsrch2

As a generalization of the ARRAY form, the CODE form
accepts any arbitrary function that maps an index to
a SCALAR reference to an element.  (The ARRAY form is
in fact eqivalent to C<sub { \$array[$_[0]] }>.)  In
the callback, C<$_> is aliased to the referent, and
C<$hi>, like in index form, must be given explicitly.

=back

=head1 CAVEATS

Prior to Perl 5.8.0, arithmetic precision is limited to the
precision of floating-point arithmetic.  This precision is
dependent on C<nv_preserves_uv_bits> of your perl, which is
53 on x86_64.  Bounds greater than C<2 ** nv_preserves_uv_bits>
will generate round-off errors and, in some cases, fail to
converge at all.  L<Math::BigInt> will be necessary in such
cases, even if both bounds technically fit in an IV/UV.

=head1 SEE ALSO

L<List::MoreUtils>, L<List::Search>, L<List::BinarySearch>,
L<List::BinarySearch::XS>.

=head1 LINKS

=over

=item *

Home page: L<https://foss.rapidcow.org/CPAN/Sort-Search/>

=item *

Git repository: L<https://codeberg.org/rapidcow/p5-Sort-Search>

=back

=cut
