=pod

=head1 NAME

Sort::Search - binary search on contiguous sorted ranges

=head1 SYNOPSIS

  use Sort::Search qw(
    bisectl bisectr bixectl bixectr
    blsrch0 brsrch0 blsrch1 brsrch1
    blsrch2 brsrch2 blsrchx brsrchx
  );

  bisectl { OK } ARRAY;   # leftmost True (F to T)
  bisectr { OK } ARRAY;   # rightmost True (T to F)
  bixectl { OK } ARRAY;   # any True  (F to T)
  bixectr { OK } ARRAY;   # any True  (T to F)

  blsrch0 { ORD } ARRAY;  # leftmost >= 0 (- to +)
  blsrch1 { ORD } ARRAY;  # leftmost > 0  (- to +)
  brsrch0 { ORD } ARRAY;  # rightmost >= 0 (+ to -)
  brsrch1 { ORD } ARRAY;  # rightmost > 0  (+ to -)

  blsrch2 { ORD } ARRAY;  # (blsrch0, blsrch1)
  brsrch2 { ORD } ARRAY;  # (brsrch0, brsrch1)
  blsrchx { ORD } ARRAY;  # any == 0  (- to +)
  brsrchx { ORD } ARRAY;  # any == 0  (+ to -)

=head1 DESCRIPTION

B<NOTE>:
This is an intentionally terse technical document.
Concrete use cases are treated in L<Sort::Search::Cookbook>.

This module implements two classes of search algorithms,
which will named separately in this document as the
I<bisection method> and the (ordinary) I<binary search>
for distinction.  A brief definition follows.

=over

=item *

The I<bisection method> works with a monotonic predicate
(B<OK>) with a unique transition point from False to True, or
vice versa.

For example, the array C<[0, 1, 2, 3, 4]> with respect to the
predicate C<< $_ >= 2 >> transitions from False at C<1> into
True at C<2>, and the array C<[5, 4, 3, 2, 1]> with respect
to the predicate C<< $_ >= 3 >> transitions from True at C<3>
to False at C<2>.  We name the boundary between these two
elements the I<bisection point>.

=item *

The I<binary search> works with a C-like comparison function,
named the I<ordering> (B<ORD>), with two unique transition
points from negative to 0, then 0 to positive.  Such a
function is typically constructed with respect to a target
value to be located within the array (hence the name "search").

For example, suppose we want to locate C<$T = 3> in the array
C<[1, 2, 3, 3, 4]>.  We can consider the ordering C<< $_ <=>
$T >>, which returns negatives for C<[1, 2]>, zeros for C<[3, 3]>,
and positives for C<[4]>.  We name the boundary between the
negatives and the zeros the I<lower bisection point>, and that
between the zeros and the positives the I<upper bisection point>.

=back

In both cases, we call the return value of the
predicate/ordering the I<comparison result>, or
C<$cmp> for short.

For every function in the conventional direction (i.e.,
left-to-right, true-to-false, increasing), a dual variant
is provided.  The conventional and dual directions are
identified by the lowercase letter L and R.  To re-use
my examples, this:

  use Sort::Search qw(bisectl);
  my @A = ( 0, 1, 2, 3, 4 );
  print $A[ bisectl { $_ >= 2 } \@A ];

prints C<2> because the left-variants prefer to return
the leftmost index of the matching range C<[2, 3, 4]>.

  use Sort::Search qw(bisectr);
  my @B = ( 5, 4, 3, 2, 1 );
  print $B[ bisectr { $_ >= 3 } \@B ];

prints C<3> because the right-variants prefer to return
the rightmost index of the matching range C<[5, 4, 3]>.

For every algorithm that searches for the precise bisection
point, a variant that returns an arbitrary match is provided.
They are identified by the letter X.  (Mnemonic: X stands
for eXists.)

=over

=item *

C<bixectl> is a modified version of C<bisectl> that
returns any index for which the predicate returns True.
In the case that the predicate attains True at exactly
one point or never attains True, they behave identically.

For C<bixectr>, it's the same against C<bisectr> except
it finds any index for which the predicate returns False.

=item *

C<blsrchx> is a modified version of C<blsrch0> that
returns any index for which the predicate returns 0.
In the case that the ordering attains 0 at exactly
one point or skips it entirely, they behave identically.

For C<brsrchx>, it's the same against C<brsrch0>.

=back

=begin VOID

The observant reader will quickly notice that the L-R
variants make each other redundant.

You are free to stick to one variant, then add 1 to or
subtract 1 from the index to derive the other. :)

For reference, the following relations should hold:

  bisectl { OK } ARRAY[,LO[,HI+1]]   ==  1 + bisectr { !OK } ARRAY[,HI[,LO-1]];
  bixectl { OK } ARRAY[,LO[,HI+1]]   ==  1 + bixectr { !OK } ARRAY[,HI[,LO-1]];
  blsrch0 { ORD } ARRAY[,LO[,HI+1]]   ==  1 + brsrch1 { -ORD } ARRAY[,HI[,LO-1]];
  blsrch1 { ORD } ARRAY[,LO[,HI+1]]   ==  1 + brsrch0 { -ORD } ARRAY[,HI[,LO-1]];
  blsrch2 { ORD } ARRAY[,LO[,HI+1]]    ==   brsrch2 { -ORD } ARRAY[,HI[,LO-1]];
                                     (in scalar context)

=end VOID

=head1 SUBROUTINES

All subroutines are exported on-demand.  All subroutines
share the same interface for input and output described in
L</COMMON INTERFACE>.  The general behavior of each subroutine
on arbitrary ranges is described, but in the common form that
I anticipate most people to use (calling with the array form
with no explicit limits, and returning in scalar context),
it is sufficient to know the following:

=over

=item *

For left searches (subroutines containing the letter "l"),
C<$lo> is the index of the leftmost/first array element and
C<$hi> is one more than the rightmost/final array element.
Notably, C<$hi> is the fallback index when search finds a
bisection point to the right of the whole array.

=item *

For right searches (subroutines containing the letter "r"),
C<$lo> is one less than the index of the leftmost/first array
element and C<$hi> is the rightmost/final array element.
Notably, C<$lo> is the fallback index when search finds a
bisection point to the left of the whole array.

=back

To re-re-use the examples from the L</DESCRIPTION> section
(assuming L<$[|perlvar/$[> is 0), the implicit search range for
C<< bisectl { ... } \@A >> is C<$lo = 0> and C<$hi = 5>, and
the implicit search range for C<< bisectr { ... } \@B >> is
C<$lo = -1> and C<$hi = 4>.  Note that the two searches
have different fallback indices: C<$hi = 5> for the left
search and C<$lo = -1> for the right search.

=over

=item B<bisectl>

=item B<bixectl>

Perform left bisection with respect to a predicate on the half-open
interval C<[$lo, $hi)>, where C<$lo> precedes C<$hi> in the argument
list.  The prototype is C<&$;$$>.

The predicate should be increasing over every pair of adjacent indices
it is defined on.  That is, true values always follow false values:

   F F F ... F T T T   ok(x)
   0 1 2     6 7 8 9      x

Let C<$ok> denote the predicate, and set C<< $ok->($hi) = 1 >>.
The return value of C<bisectl> is the unique index C<$x> on the
closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ok->($x) >> is true.

=item *

For all valid index C<< $y < $x >>, it follows that C<< $ok->($y) >> is false.

=back

The return value of C<bixectl> is any index satisfying the first constraint.

If the interval C<[$lo, $hi]> is empty, return C<$hi>.

=item B<bisectr>

=item B<bixectr>

Perform right bisection with respect to a predicate on the half-open
interval C<($lo, $hi]>, where C<$hi> precedes C<$lo> in the argument
list.  The prototype is C<&$;$$>.

The predicate should be decreasing over every pair of adjacent indices
it is defined on.  That is, true values always precede false values:

   T T T ... T F F F   ok(x)
   0 1 2     6 7 8 9      x

Let C<$ok> denote the predicate, and set C<< $ok->($lo) = 1 >>.
The return value of C<bisectr> is the unique index C<$x> on the
closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ok->($x) >> is true.

=item *

For all valid index C<< $y > $x >>, it follows that C<< $ok->($y) >> is false.

=back

The return value of C<bixectr> is any index satisfying the first constraint.

If the interval C<[$lo, $hi]> is empty, return C<$lo>.

=back

In general, a return value of C<$hi> (for left bisection) and
C<$lo> (for right bisection) is not meaningful as it is the only
index taken to be true for granted.  Caller should handle it
separately, or check if the comparison result and/or element
are defined by calling in list context.

=over

=item B<blsrch0>

=item B<blsrchx>

=item B<blsrch1>

=item B<blsrch2>

Perform binary left search with respect to an ordering on the
half-open interval C<[$lo, $hi)>, where C<$lo> precedes C<$hi>
in the argument list.  The prototype is C<&$;$$>.

The sign of the ordering should be increasing over every pair of
adjacent indices it is defined on.  That is, C<< <0 >> (negative)
precedes C<< =0 >> (zero), which precedes C<< >0 >> (positive).

More concretely, the ordering defines the comparison of every value in
an ordered list, C<$_>, to a target value, C<$target>: C<< $cmp < 0 >>
represents C<< $_ < $target >>; C<$cmp == 0> represents C<$_ == $target>;
and C<< $_ > $target >> when C<< $cmp > 0 >>.  When the list is sorted
in increasing order, C<< $_ <=> $target >> is a valid ordering:

   [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 8, 9, 9]       x
   -1 -1 -1  ...  -1  0  0  0  1  1  ...     ord(x) := (x <=> 5)

When the list is sorted in decreasing order, C<< $target <=> $_ >>
is a valid ordering:

   [9, 9, 8, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1]       x
    ...  -1 -1  0  0  0  1  ...   1  1  1    ord(x) := (5 <=> x)

The same applies to sorted lists of strings by replacing
C<< <=> >> with C<cmp>.

Let C<$ord> denote the ordering and set C<< $ord->($hi) = +Infinity >>.
The return value of C<blsect0> is the unique index C<$lower> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($lower) >= 0 >>.

=item *

For all valid index C<< $x < $lower >>, it follows that C<< $ord->($x) < 0 >>.
As a result, C<< $lower >> is the first instance where C<< $ord >= 0 >>,
while C<< $lower - 1 >> is the last instance where C<< $ord < 0 >>.
(Compare this to C<brsect1>.)

=back

The return value of C<blsectx> is any index C<$x> satisfying
C<< $ord->($x) == 0 >>, but if one could not be found,
it returns the same result as C<blsect0>.

The return value of C<blsect1> is the unique index C<$upper_x>
on the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($upper_x) > 0 >>.

=item *

For all valid index C<< $x < $upper_x >>, it follows that C<< $ord->($x) <= 0 >>.
As a result, C<< $upper_x >> is the first instance where C<< $ord > 0 >>,
while C<< $upper_x - 1 >> is the last instance where C<< $ord <= 0 >>.
(Compare this to C<brsect0>.)

=back

In list context, C<blsect2> returns both C<$lower> and C<$upper>,
in that order.  In scalar context, it returns the nonnegative
difference C<$upper_x - $lower>, which equals the number of elements
for which C<$ord == 0>.

=item B<brsrch0>

=item B<brsrchx>

=item B<brsrch1>

=item B<brsrch2>

Perform binary right search with respect to an ordering on the
half-open interval C<($lo, $hi]>, where C<$hi> precedes C<$lo>
in the argument list.  The prototype is C<&$;$$>.

The sign of the ordering should be decreasing over every pair of
adjacent indices it is defined on.  That is, C<< >0 >> (positive)
precedes C<< =0 >> (zero), which precedes C<< <0 >> (negative).

More concretely, the ordering defines the comparison of every value in
an ordered list, C<$_>, to a target value, C<$target>: C<< $cmp < 0 >>
represents C<< $_ < $target >>; C<$cmp == 0> represents C<$_ == $target>;
and C<< $_ > $target >> when C<< $cmp > 0 >>.  When the list is sorted
in increasing order, C<< $target <=> $_ >> is a valid ordering:

   [1, 1, 2, 3, 3, 4, 5, 5, 5, 6, 8, 9, 9]       x
    1  1  1  ...   1  0  0  0 -1 -1  ...     ord(x) := (5 <=> x)

When the list is sorted in decreasing order, C<< $_ <=> $target >>
is a valid ordering:

   [9, 9, 8, 6, 5, 5, 5, 4, 3, 3, 2, 1, 1]       x
    ...   1  1  0  0  0 -1  ...  -1 -1 -1    ord(x) := (x <=> 5)

The same applies to sorted lists of strings by replacing
C<< <=> >> with C<cmp>.

Let C<$ord> denote the ordering and set C<< $ord->($lo) = +Infinity >>.
The return value of C<brsect0> is the unique index C<$upper> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($upper) >= 0 >>.

=item *

For all valid index C<< $x > $upper >>, it follows that C<< $ord->($x) < 0 >>.
As a result, C<< $upper >> is the last instance where C<< -$ord <= 0 >> and
C<< $upper + 1 >> is the first instance where C<< -$ord > 0 >>.
(Compare this to C<blsect1>.)

=back

The return value of C<brsectx> is any index C<$x> satisfying
C<< $ord->($x) == 0 >>, but if one could not be found,
it returns the same result as C<brsect0>.

The return value of C<brsect1> is the unique index C<$lower> on
the closed interval C<[$lo, $hi]> such that:

=over

=item *

C<< $ord->($lower_x) > 0 >>.

=item *

For all valid index C<< $x > $lower_x >>, it follows that C<< $ord->($x) <= 0 >>.
As a result, C<< $lower_x >> is the last instance where C<< -$ord < 0 >> and
C<< $lower_x + 1 >> is the first instance where C<< -$ord >= 0 >>.
(Compare this to C<blsect0>.)

=back

In list context, C<brsect2> returns both C<$upper> and C<$lower_x>,
in that order.  In scalar context, it returns the nonnegative
difference C<$upper - $lower_x>, which equals the number of elements
for which C<$ord == 0>.

=back

=head1 COMMON INTERFACE

  # TODO !

=head1 CAVEATS

  # TODO !

=head1 SEE ALSO

L<List::MoreUtils>, L<List::Search>, L<List::BinarySearch>,
L<List::BinarySearch::XS>.

=head1 LINKS

More about this distribution can be found at:

=over

=item *

Home page: L<https://pub.rapidcow.org/CPAN/Sort-Search/>

=item *

Git repository: L<https://github.com/rapidcow/p5-Sort-Search>

=back

=cut
